### PR TITLE
This lets you run embed and rerank locally.

### PR DESCRIPTION
**Pull request by freemansoft**
I wanted to demonstrate/run everything local so there was no chance of data leakage.

There is a bit of a hack in here because the NGC_API_KEY needs two have two different values in two different places.  The rerank and embed services need a non `nvapi-` key to pull down their models on startup.  The chat front end requires a `nvapi-` key to talk to the remote nvidia endpoints.  Chat startup fails if the key doesn't start with `nvapi-`. So I added a second NGC_API_KEY_2 with a description of where to get the key

Tested on Ubuntu with a TITAN RTX card.

### CODE REVIEW

**Comment by freemansoft** [comment]
This PR may conflict with https://github.com/NVIDIA/nim-anywhere/pull/31

**Comment by rmkraus** [comment]
Thanks Joe. The trick here is that the nvapi keys are tied to specific teams in NGC. The old style keys are not specific to a team. 

So you'll need to create your nvapi key in the team that you are a member of that has access to the embed and rerank services.

**Comment by freemansoft** [comment]
I have literally nine different keys I created by poking around. None of the them work for everything :-( I'm not sure I'm even in a team let alone one that has access to the embed and rerank service.

**Comment by freemansoft** [comment]
> So you'll need to create your nvapi key in the team that you are a member of that has access to the embed and rerank services.

I have no idea what this means or how to do it.  I have a team but I don't see any way to assign keys to a team.

**Pull request closed without merging**
